import enum


class OfferState(str, enum.Enum):
    """États d'une offre — nomenclature anglaise (V2)."""

    DETECTED = "DETECTED"
    RAW_STORED = "RAW_STORED"
    NORMALIZED = "NORMALIZED"
    DEDUPLICATED = "DEDUPLICATED"
    ANALYZED = "ANALYZED"
    REJECTED = "REJECTED"
    QUALIFIED = "QUALIFIED"
    DRAFT_REQUESTED = "DRAFT_REQUESTED"
    DRAFT_PREPARED = "DRAFT_PREPARED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    SUBMISSION_IN_PROGRESS = "SUBMISSION_IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    CLOSED = "CLOSED"
